apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cast
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cast
    spec:
      containers:
      - name: cast
        image: {{ .Values.cast.image.repository }}:{{ .Values.cast.image.tag }}
        imagePullPolicy: {{ .Values.cast.image.pullpolicy }}
        command: ["uvicorn", "app.main:app", "--reload", "--host", "{{ .Values.cast.host }}", "--port", "{{ .Values.cast.targetport }}"]
        env:
        - name: DATABASE_URI
          value: {{ .Values.cast.database.uri }}
        ports:
        - containerPort: {{ .Values.cast.targetport }}
        volumeMounts:
        - name: cast-mnt
          mountPath: /app-storage/
      volumes:
        - name: cast-mnt
          persistentVolumeClaim:
            claimName: cast-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-app
spec:
  selector:
    app: {{ .Release.Name }}-cast
  ports:
  - protocol: TCP
    port: {{ .Values.cast.port }}
    targetPort: {{ .Values.cast.targetport }}
