apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./cast-app/"
  claimRef:
    name: cast-pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
