apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-movie-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./movie-db"
  claimRef:
    name: movie-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
