movie:
  image:
    repository: "mloche/jenkins-exam-movies-app"
    tag: "latest"
  host: "0.0.0.0"
  port: 8000
  targetport: 8000
  database:
    uri: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
