cast:
  image:
    repository: "mloche/jenkins-exam-casts-app"
    tag: "latest"
    pullpolicy: "Always"
  host: "0.0.0.0"
  port: 8002
  targetport: 8000
  database:
    uri: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"
