apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
     listen 8080;

      location /api/v1/movies {
         proxy_pass http://{{ .Release.Name }}-movie-app:8000/api/v1/movies;
        }

      location /api/v1/casts {
         proxy_pass http://{{ .Release.Name }}-cast-app:8002/api/v1/casts;
         }

       }
