apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie
    spec:
      containers:
      - name: cast
        image: {{ .Values.movie.image.repository }}:{{ .Values.movie.image.tag }}
        imagePullPolicy: {{ .Values.movie.image.pullpolicy }}
        command: ["uvicorn", "app.main:app", "--reload", "--host", "{{ .Values.movie.host }}", "--port", "{{ .Values.movie.targetport }}"]
        env:
        - name: DATABASE_URI
          value: {{ .Values.movie.database.uri }}
        - name: CAST_SERVICE_HOST_URL
          value: 'http://{{ .Release.Name }}-cast-app:8002/api/v1/casts/'
        ports:
        - containerPort: {{ .Values.movie.targetport }}
        volumeMounts:
        - name: movie-mnt
          mountPath: /app-storage
      volumes:
        - name: movie-mnt
          persistentVolumeClaim:
            claimName: movie-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-app
spec:
  selector:
    app: {{ .Release.Name }}-movie
  ports:
  - protocol: TCP
    port: {{ .Values.movie.port }}
    targetPort: {{ .Values.movie.targetport }}
