apiVersion: v1
kind: PersistentVolume
metadata:
  name: movie-pv-{{ .Release.Name }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./movie-app/"
  claimRef:
    name: movie-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
